from __future__ import annotations

from datetime import datetime
import re
from pathlib import Path
from typing import Any

from .config import DEFAULT_REPORT_DIR


def _table(headers: list[str], rows: list[list[Any]]) -> str:
    header_line = "| " + " | ".join(headers) + " |"
    sep = "| " + " | ".join(["---"] * len(headers)) + " |"
    body = ["| " + " | ".join(str(x).replace("\n", " ") for x in row) + " |" for row in rows]
    return "\n".join([header_line, sep, *body])


def _sanitize_repo_name(repo_path: str | Path) -> str:
    repo_name = Path(repo_path).resolve().name.strip()
    repo_name = re.sub(r"\s+", "_", repo_name)
    repo_name = re.sub(r"[^A-Za-z0-9_-]+", "_", repo_name)
    repo_name = re.sub(r"_+", "_", repo_name).strip("_")
    return repo_name or "repository"


def generate_markdown_report(
    repo_path: str,
    analysis: dict[str, Any],
    commits: list[dict[str, Any]],
    story: str,
    output_path: str | Path | None = None,
) -> Path:
    """Generate a Markdown report and return the saved path."""
    if output_path is None:
        repo_name = _sanitize_repo_name(repo_path)
        output_path = DEFAULT_REPORT_DIR / f"{repo_name}_code_history_report.md"
    output = Path(output_path).resolve()
    output.parent.mkdir(parents=True, exist_ok=True)

    author_rows = [[author, count] for author, count in analysis.get("authors", {}).items()]
    file_rows = [[file, count] for file, count in analysis.get("top_files", [])]
    month_rows = [[month, count] for month, count in analysis.get("activity_by_month", {}).items()]
    commit_rows = [
        [c["short_hash"], c["date"], c["author"], c["message"][:90], len(c.get("files_changed", []))]
        for c in commits[-25:]
    ]

    markdown = f"""# ChronoCode AI Report

**Repository:** `{repo_path}`  
**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

---

## Summary

| Metric | Value |
|---|---:|
| Total Commits | {analysis.get('total_commits', 0)} |
| Total Authors | {analysis.get('total_authors', 0)} |
| Total Insertions | {analysis.get('total_insertions', 0)} |
| Total Deletions | {analysis.get('total_deletions', 0)} |
| First Commit | {analysis.get('first_commit_date')} |
| Latest Commit | {analysis.get('latest_commit_date')} |

---

## Codebase Story

{story}

---

## Author Activity

{_table(['Author', 'Commits'], author_rows) if author_rows else 'No author data found.'}

---

## Most Changed Files

{_table(['File', 'Change Count'], file_rows) if file_rows else 'No file change data found.'}

---

## Monthly Activity

{_table(['Month', 'Commits'], month_rows) if month_rows else 'No monthly activity found.'}

---

## Recent Commit Timeline

{_table(['Hash', 'Date', 'Author', 'Message', 'Files'], commit_rows) if commit_rows else 'No commits found.'}

---

Generated by **ChronoCode AI**.
"""

    output.write_text(markdown, encoding="utf-8")
    return output
